application: pequenos-peludos
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /Utilities
  static_dir: Utilities

- url: /favicon\.ico
  static_files: dog2.png
  upload: dog2\.png


- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
